version: '3'
services:
  app-postgres:
    image: postgres:latest
    container_name: app-postgres
    ports:
      - 5432:5432
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  emitter:
    container_name: emitter
    build: ./emitter
    ports:
    - 8080:8080
    restart: on-failure

  listener:
    container_name: listener
    build: ./listener
    ports:
    - "0.0.0.0:53612:53612"
    restart: on-failure
    depends_on:
      - app-postgres
      - emitter
    environment:
    - EMITTER_HOST=${EMITTER_HOST}
    - EMITTER_PORT=${EMITTER_PORT}
    - POSTGRES_HOST=${POSTGRES_HOST}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}